// Central source registry — the single place that says where each card's data
// comes from. Both the per-card source caption (desktop hero + mobile deck) and
// the global "Quellen" overlay read from here, so a source is written once.
//
// `S` is the institution registry (name + official link); `CARD_SOURCES` maps a
// card id to its institution; `SOURCE_GROUPS` is the grouped list the overlay
// renders. Kept dependency-free (no imports from dashboards/data) so it never
// participates in the dashboards ↔ data import cycle.

export interface Source {
  name: string;
  url?: string;
}

/** Institutions, each cited once with its official landing page. */
const S = {
  // Live APIs
  treasury: { name: 'US Treasury · Fiscal Data', url: 'https://fiscaldata.treasury.gov' },
  worldBank: { name: 'Weltbank', url: 'https://data.worldbank.org' },
  wikimedia: { name: 'Wikimedia REST API', url: 'https://wikimedia.org/api/rest_v1' },
  openMeteo: { name: 'Open-Meteo', url: 'https://open-meteo.com' },
  // Freedom, democracy, press
  freedomHouse: { name: 'Freedom House', url: 'https://freedomhouse.org/report/freedom-world' },
  vdem: { name: 'V-Dem Institute', url: 'https://v-dem.net' },
  rsf: { name: 'Reporter ohne Grenzen (RSF)', url: 'https://rsf.org' },
  cpj: { name: 'Committee to Protect Journalists (CPJ)', url: 'https://cpj.org' },
  accessNow: { name: 'Access Now · #KeepItOn', url: 'https://accessnow.org/keepiton' },
  icnl: { name: 'ICNL · COVID-19 Civic Freedom Tracker', url: 'https://icnl.org' },
  bundestag: { name: 'Bundestag / Landesjustiz', url: 'https://bundestag.de' },
  penAmerica: { name: 'PEN America', url: 'https://pen.org' },
  googleReport: { name: 'Google Transparency Report', url: 'https://transparencyreport.google.com' },
  transparencyReports: { name: 'Transparenzberichte (Google/Apple/Meta)' },
  ukPolice: { name: 'UK-Polizei · FOI (via The Times)' },
  // Money & economy
  fed: { name: 'Federal Reserve · FRED', url: 'https://fred.stlouisfed.org' },
  ecb: { name: 'EZB · SPACE-Studie', url: 'https://ecb.europa.eu' },
  riksbank: { name: 'Sveriges Riksbank', url: 'https://riksbank.se' },
  worldpay: { name: 'FIS / Worldpay · Global Payments Report', url: 'https://worldpay.com' },
  bankRussia: { name: 'Bank of Russia', url: 'https://cbr.ru' },
  imf: { name: 'IWF · World Economic Outlook', url: 'https://imf.org/en/Publications/WEO' },
  forbes: { name: 'Forbes', url: 'https://forbes.com/billionaires' },
  atlanticCouncil: { name: 'Atlantic Council · CBDC Tracker', url: 'https://atlanticcouncil.org/cbdctracker' },
  creditreform: { name: 'Creditreform', url: 'https://creditreform.de' },
  hanke: { name: 'Dokumentierte Hyperinflationen (Hanke-Krus)', url: 'https://en.wikipedia.org/wiki/Hyperinflation' },
  wto: { name: 'World Trade Organization (WTO)', url: 'https://wto.org' },
  ubs: { name: 'UBS Global Wealth Report', url: 'https://ubs.com' },
  bls: { name: 'US Bureau of Labor Statistics', url: 'https://bls.gov' },
  drv: { name: 'Deutsche Rentenversicherung', url: 'https://deutsche-rentenversicherung.de' },
  empirica: { name: 'empirica-Regio (Schätzung)' },
  // Germany
  destatis: { name: 'Destatis · Statistisches Bundesamt', url: 'https://destatis.de' },
  ba: { name: 'Bundesagentur für Arbeit', url: 'https://statistik.arbeitsagentur.de' },
  pks: { name: 'Polizeiliche Kriminalstatistik (BKA)', url: 'https://bka.de' },
  lkaNRW: { name: 'LKA Nordrhein-Westfalen', url: 'https://lka.polizei.nrw' },
  bnetza: { name: 'Bundesnetzagentur', url: 'https://bundesnetzagentur.de' },
  berlinSenat: { name: 'Senatsverwaltung Berlin', url: 'https://berlin.de' },
  // World & society
  unwpp: { name: 'UN World Population Prospects', url: 'https://population.un.org/wpp' },
  unhcr: { name: 'UNHCR', url: 'https://unhcr.org/refugee-statistics' },
  oecd: { name: 'OECD', url: 'https://data.oecd.org' },
  eurostat: { name: 'Eurostat', url: 'https://ec.europa.eu/eurostat' },
  fao: { name: 'FAO', url: 'https://fao.org' },
  owid: { name: 'Our World in Data', url: 'https://ourworldindata.org' },
  energyInst: { name: 'Energy Institute · Statistical Review', url: 'https://energyinst.org/statistical-review' },
  itu: { name: 'ITU', url: 'https://itu.int' },
  sipri: { name: 'SIPRI', url: 'https://sipri.org' },
  fas: { name: 'Federation of American Scientists (FAS)', url: 'https://fas.org' },
  cdc: { name: 'US CDC', url: 'https://cdc.gov' },
  who: { name: 'WHO', url: 'https://who.int' },
  comparitech: { name: 'Comparitech', url: 'https://comparitech.com' },
  ihs: { name: 'IHS Markit' },
  walkFree: { name: 'Walk Free · Global Slavery Index', url: 'https://walkfree.org' },
  prisonBrief: { name: 'World Prison Brief', url: 'https://prisonstudies.org' },
  transparency: { name: 'Transparency International', url: 'https://transparency.org' },
  dod: { name: 'US DoD · DMDC', url: 'https://dmdc.osd.mil' },
  iiss: { name: 'IISS Military Balance', url: 'https://iiss.org' },
  oxcgrt: { name: 'Oxford · OxCGRT', url: 'https://bsg.ox.ac.uk' },
  cleanCities: { name: 'Clean Cities Campaign', url: 'https://cleancitiescampaign.org' },
  fda: { name: 'US FDA', url: 'https://fda.gov' },
  c40: { name: 'C40 Cities', url: 'https://c40.org' },
  census: { name: 'US Census · American Housing Survey', url: 'https://census.gov' },
  samhsa: { name: 'SAMHSA · NSDUH', url: 'https://samhsa.gov' },
  commonSense: { name: 'Common Sense Media', url: 'https://commonsensemedia.org' },
  gsma: { name: 'GSMA (Schätzwerte)', url: 'https://gsma.com' },
  dataReportal: { name: 'DataReportal (Schätzung)', url: 'https://datareportal.com' },
  un: { name: 'Vereinte Nationen', url: 'https://un.org' },
} as const;

/** Card id → its data source. Unlisted cards simply show no caption. */
export const CARD_SOURCES: Record<string, Source> = {
  military: S.sipri,
  'military-per-soldier': S.sipri,
  'military-gdp': S.sipri,
  'us-debt': S.treasury,
  nukes: S.fas,
  'homicide-map': S.worldBank,
  'swiss-pop': S.worldBank,
  'world-pop': S.owid,
  'oil-consumption': S.energyInst,
  'conflict-deaths': S.owid,
  refugees: S.unhcr,
  'refugees-interventions': S.unhcr,
  'us-interest': S.treasury,
  overdose: S.cdc,
  'debt-gdp': S.imf,
  'eu-debt-map': S.eurostat,
  'pop-share': S.unwpp,
  'life-exp': S.owid,
  'life-exp-nations': S.unwpp,
  m2: S.fed,
  'm2-history': S.fed,
  'ai-jobs': S.bls,
  'youth-unemployment': S.oecd,
  unemployment: S.oecd,
  poverty: S.oecd,
  'de-insolvenz-jobs': S.creditreform,
  'de-underemployment': S.ba,
  'de-industry': S.oecd,
  'de-exports': S.wto,
  'de-migration': S.destatis,
  'de-migration-flows': S.destatis,
  'de-population': S.destatis,
  'de-crime-foreign': S.pks,
  'de-assault': S.pks,
  'de-knife-attacks': S.lkaNRW,
  'de-tax-quota': S.oecd,
  'de-power-prices': S.eurostat,
  'berlin-warrants': S.berlinSenat,
  'de-state-quota': S.destatis,
  'de-old-age-ratio': S.destatis,
  'de-aging-nations': S.unwpp,
  'internet-shutdowns': S.accessNow,
  'press-freedom-nations': S.rsf,
  'jailed-journalists': S.cpj,
  'asset-correlation': S.fed,
  'book-bans': S.penAmerica,
  internet: S.itu,
  'world-hunger': S.fao,
  'extreme-poverty': S.worldBank,
  'nuke-tests': S.fas,
  fertility: S.unwpp,
  dollar: S.bls,
  'real-wages': S.destatis,
  homeownership: S.eurostat,
  'cb-balance': S.fed,
  'wealth-divergence': S.forbes,
  'food-fertilizer': S.fao,
  'pension-level': S.drv,
  'rent-burden': S.empirica,
  armies: S.iiss,
  wealth: S.ubs,
  incarceration: S.prisonBrief,
  'obesity-nations': S.who,
  'tax-burden': S.oecd,
  'power-prices': S.eurostat,
  corruption: S.transparency,
  'modern-slavery': S.walkFree,
  'us-bases': S.dod,
  'us-wars': S.owid,
  'recent-wars': S.owid,
  'teen-mde': S.samhsa,
  'female-lfp': S.destatis,
  'teen-screen': S.commonSense,
  'teen-antidepressants': S.cdc,
  'de-energy-mix': S.bnetza,
  'obesity-fastfood': S.cdc,
  surveillance: S.comparitech,
  'cameras-world': S.ihs,
  'gov-requests-country': S.transparencyReports,
  'youtube-removals': S.googleReport,
  '5g-stations': S.gsma,
  inflation: S.imf,
  'un-resolutions': S.un,
  'de-family': S.destatis,
  'single-households': S.destatis,
  'digital-id': S.worldBank,
  'alcohol-nations': S.who,
  'alcohol-deaths': S.cdc,
  'c40-cities': S.c40,
  'covid-stringency': S.oxcgrt,
  'covid-lockdowns': S.owid,
  'covid-vax-percapita': S.owid,
  cashless: S.ecb,
  'fiat-lifespan': S.hanke,
  cbdc: S.atlanticCouncil,
  'freedom-decline': S.freedomHouse,
  'covid-rights': S.icnl,
  'de-speech-cases': S.bundestag,
  'uk-speech-arrests': S.ukPolice,
  'young-homeownership': S.census,
  'lez-zones': S.cleanCities,
  'shutdowns-per-year': S.accessNow,
  'gene-therapies': S.fda,
  'autocracy-share': S.vdem,
  'smartphone-leash': S.dataReportal,
};

/** Grouped view for the Quellen overlay. */
export const SOURCE_GROUPS: { title: string; items: Source[] }[] = [
  { title: 'Live-APIs (bei jedem Laden aktualisiert)', items: [S.treasury, S.worldBank, S.wikimedia, S.openMeteo] },
  { title: 'Freiheit, Demokratie & Presse', items: [S.freedomHouse, S.vdem, S.rsf, S.cpj, S.accessNow, S.icnl, S.penAmerica, S.googleReport, S.bundestag, S.ukPolice] },
  { title: 'Geld & Wirtschaft', items: [S.fed, S.ecb, S.riksbank, S.worldpay, S.bankRussia, S.imf, S.forbes, S.atlanticCouncil, S.creditreform, S.wto, S.ubs, S.bls, S.drv, S.hanke] },
  { title: 'Deutschland', items: [S.destatis, S.ba, S.pks, S.lkaNRW, S.bnetza, S.berlinSenat] },
  { title: 'Welt, Gesellschaft & Gesundheit', items: [S.unwpp, S.unhcr, S.oecd, S.eurostat, S.fao, S.owid, S.energyInst, S.itu, S.sipri, S.fas, S.cdc, S.who, S.samhsa, S.commonSense, S.walkFree, S.prisonBrief, S.transparency, S.dod, S.iiss, S.comparitech, S.oxcgrt, S.cleanCities, S.fda, S.c40, S.census, S.un] },
];

/**
 * The data are curated support points from the primary sources above — partly
 * rounded or interpolated between years. Reliable for the shape and order of
 * magnitude of each curve, not to the decimal.
 */
export const SOURCE_DISCLAIMER =
  'Die Reihen sind kuratierte Stützpunkte aus den genannten Primärquellen — teils gerundet oder interpoliert. Verlässlich für Form und Größenordnung, nicht auf die Nachkommastelle.';
